process.env.NODE_ENV = 'test';
import './core.test.js';
import './http.test.js';
import './realtime.test.js';
import './account.test.js';
import './image-storage.test.js';
import './upload-cleanup.test.js';
import './seed-data.test.js';
import './totp.test.js';
import './webauthn.test.js';
import './security-regression.test.js';
import './board-digest.test.js';
import './duplicate-check.test.js';
