import type { AnyRecord } from './types';
import { getPosterToken, readAccountToken, readAdminToken } from './storage';

export const state: AnyRecord = {
  boards: [],
  boardGroups: [],
  initialHomeSnapshot: null,
  aiConfigured: false,
  hcaptchaSiteKey: '',
  hcaptchaReady: null,
  boardSlug: 'confession',
  threadId: '',
  threadDetail: null,
  threadLoadRequestId: 0,
  threadGlobalNumber: '',
  threadPosterHash: '',
  threadLastSeenBefore: 0,
  threadCurrentMaxNumber: 0,
  token: readAdminToken(),
  accountToken: readAccountToken(),
  account: null,
  accountPostNumbers: new Set(),
  temp2FAToken: null,
  adminTemp2FAToken: null,
  accountPrivateData: null,
  accountPrivateSaveTimer: null,
  posterToken: getPosterToken(),
  selectedImage: [],
  commentImage: [],
  quickReplyImage: [],
  maxImageBytes: 0,
  audioRecorders: {},
  audioTranscribing: new Set(),
  audioTranscriptionControllers: new Map(),
  refPreviewCache: new Map(),
  refPreviewRequestId: 0,
  refPreviewHideTimer: null,
  refPreviewShowTimer: null,
  refPreviewPinned: false,
  refPreviewHoverNumber: '',
  quickReplyDrag: null,
  quickReplyInvoker: null,
  /** True when quick-reply was opened from the board list (not thread screen). */
  quickReplyFromBoard: false,
  replyComposerOpen: false,
  replyComposerInvoker: null,
  replyComposerTargetNumber: '',
  replyComposerInlineTarget: null,
  pendingInlineReply: null,
  threadIsArchived: false,
  threadIsLocked: false,
  boardPage: 1,
  boardPageSize: 15,
  boardSearchTerm: '',
  boardSort: 'bump',
  boardFilter: 'all',
  boardPageMeta: null,
  threadCommentPage: 1,
  threadCommentPageSize: 50,
  threadCommentPageMeta: null,
  threadSearchTerm: '',
  commentsSort: 'old',
  autoTimer: null,
  realtimeSource: null,
  realtimeContextKey: '',
  browserNotificationIds: new Set(),
  watchedThreadSummaries: [],
  boardThreads: [],
  boardThreadsCache: new Map(),
  catalogThreads: [],
  catalogSort: 'bump',
  catalogImageSize: 'small',
  catalogFilter: 'all',
  theme: localStorage.getItem('theme') || 'yotsuba-b',
  archiveThreads: [],
  adminTab: 'pending',
  adminItems: [],
  moderationConfidenceThreshold: 0,
  lifecycle: {
    maxActiveThreadsPerBoard: 150,
    bumpLimit: 300,
    replyLimit: 500
  }
};
